mq:
  defaultExchange: amqpExchange
  queues: yueguangQueue,caiyunQueue,orderMigrationQueue,TestQueue
  queueAndRouteKey:
    yueguangRouteKey: yueguangQueue
    caiyunRouteKey: caiyunQueue
    orderMigrationKey: orderMigrationQueue
