mq:
  defaultExchange: amqpExchange
  queues: yueguangQueue,caiyunQueue,orderMigrationQueue,TestQueue,deadQueue
  queueAndRouteKey:
    yueguangRouteKey: yueguangQueue
    caiyunRouteKey: caiyunQueue
    orderMigrationKey: orderMigrationQueue
    TestQueue: TestQueue
  deadExchange: deadExchange
  deadExchangeLabel: x-dead-letter-exchange
  deadRoutingKeyLabel: x-dead-letter-routing-key
  deadQueue: deadQueue
  deadRoutingKey: deadRoutingKey